record_start:
  description: Start recording a stream to a file.
  fields:
    camera_entity_id:
      description: Camera entity to record (preferred).
      example: camera.front_door
      selector:
        entity:
          domain: camera
    stream_url:
      description: Stream URL (used if no camera entity is provided).
      example: rtsp://172.16.10.230:8554/front_door?mp4
      required: false
      selector:
        text:
    filename:
      description: File path to record to.
      example: /media/front_door.mp4
      required: true
      selector:
        text:

record_stop:
  description: Stop an active recording.
  fields:
    camera_entity_id:
      description: Camera entity to stop (preferred).
      example: camera.front_door
      selector:
        entity:
          domain: camera
    stream_url:
      description: Stream URL to stop (used if no camera entity is provided).
      example: rtsp://172.16.10.230:8554/front_door?mp4
      required: false
      selector:
        text:
