record_start:
  description: Start recording a stream to a file.
  fields:
    stream_url:
      description: RTSP stream URL.
      example: rtsp://192.168.10.230:8554/front_door_no_mic?mp4
      required: true
      selector:
        text:
    filename:
      description: File path to record to.
      example: /media/front_door_20250614.mp4
      required: true
      selector:
        text:

record_stop:
  description: Stop recording from a given stream.
  fields:
    stream_url:
      description: RTSP stream URL to stop.
      example: rtsp://192.168.10.230:8554/front_door_no_mic?mp4
      required: true
      selector:
        text:
